openapi: 3.0.0
info:
  description: 'Carbon Aware REST API'
  version: 0.1.0
  title: Carbon Aware REST API

paths:
  '/sci-scores':
    post:
      summary: Calculate the SCI score using the configured plugins
      description: ''
      operationId: calculateSciScore
      requestBody:
        '$ref': '#/components/requestBodies/SciScoreCalculationPlugin'
        examples: 
          sci-score-calculation:
            '$ref': '#/components/examples/sci-score-calc-example'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  '$ref': '#/components/schemas/SciScore'
              examples: 
                sci-score-response:
                  '$ref': '#/components/examples/sci-score-response-example'

components:
  requestBodies:
    SciScoreCalculationPlugin:
      content:
        application/json:
          schema:
            '$ref': '#/components/schemas/SciScoreCalculationPlugin'
      description: Sci Score calculation component payload for configured plugin
      required: true
  schemas:
    SciScore:
      type: object
      properties:
        sciScore:
          type: number
          format: float
        energyValue:
          type: number
          format: float
        marginalCarbonIntensityValue:
          type: number
          format: float
        embodiedEmissions:
          type: number
          format: float
        functionalUnit:
          type: integer
          format: int64

    SciScoreCalculationPlugin:
      type: object
      properties:
        azRegion:
          type: string
          enum:
            - northeurope
            - westeurope
        duration:
          type: string
          description: ISO8601 formatted [time interval](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)
          example: 2007-03-01T13:00:00Z/2007-03-01T15:30:00Z
    
  examples:
    sci-score-calc-example:
      summary: A calculation payload example using a plugin which only calculates for (I) and uses default values for (E,M, & R).
      value: {
        "azRegion": "northeurope",
        "duration": "2022-03-01T13:00:00Z/2022-03-01T13:30:00Z"
      }
    sci-score-response-example:
      summary: An example response from an SCI score calculation request
      value: {
        "sciScore": 750.0,
        "energyValue": 1.0,
        "marginalCarbonIntensityValue": 750.0,
        "embodiedEmissionsValue": 0.0,
        "functionalUnitValue": 1 
      }
